/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'weli' at '1/12/17 11:23 PM' with Gradle 2.14.1
 *
 * @author weli, @date 1/12/17 11:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
