import org.apache.commons.daemon.Daemon;
import org.apache.commons.daemon.DaemonContext;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'weli' at '1/12/17 11:23 PM' with Gradle 2.14.1
 *
 * @author weli, @date 1/12/17 11:23 PM
 */
public class MyDaemon implements Daemon {

    @Override
    public void init(DaemonContext context) throws Exception {
        System.out.println("MyDaemon init...");
    }

    @Override
    public void start() throws Exception {
        System.out.println("MyDaemon start...");
    }

    @Override
    public void stop() throws Exception {
        System.out.println("MyDaemon stop...");
    }

    @Override
    public void destroy() {
        System.out.println("MyDaemon destroy...");
    }
}
